# Generated by Django 5.1.7 on 2025-04-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MessageSent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email_sender", models.EmailField(max_length=254)),
                ("first_name_sender", models.CharField(max_length=160)),
                ("last_name_sender", models.CharField(max_length=160)),
                ("message", models.TextField()),
                ("date_sent", models.DateTimeField(auto_now_add=True)),
                ("user_authenticated", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Message Sent",
                "verbose_name_plural": "Messages Sent",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SocialShare",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("platform", models.CharField(max_length=100)),
                ("share_count", models.IntegerField(default=0)),
            ],
        ),
    ]
