# Generated by Django 5.1.7 on 2025-04-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action", models.TextField()),
                ("action_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
