# Generated by Django 5.1.6 on 2025-02-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conscious_element", "0002_profile_session_userrole_follow"),
    ]

    operations = [
        migrations.AddField(
            model_name="cryptekuser",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
    ]
