# Generated by Django 5.1.7 on 2025-04-01 12:08

import django.db.models.deletion
import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("subtitle", models.CharField(max_length=20)),
                ("description", models.TextField(blank=True)),
                ("slug", models.SlugField()),
                ("thumbnail", models.ImageField(upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="Entry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("content", markdownx.models.MarkdownxField()),
                ("overview", models.TextField(blank=True, max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.IntegerField(choices=[(0, "Draft"), (1, "Published"), (2, "hidden")], default=0)),
                ("featured", models.BooleanField(default=False)),
                ("publish_date", models.DateTimeField(blank=True, null=True)),
                ("header_image", models.ImageField(blank=True, null=True, upload_to="header_images/")),
                ("slug", models.SlugField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Entries",
                "ordering": ["-created_at"],
                "get_latest_by": "created_at",
            },
        ),
        migrations.CreateModel(
            name="EntryAnalytics",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("views", models.IntegerField(default=0)),
                ("read_time", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="EntryReaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reaction", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="EntryVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content", models.TextField()),
                ("version_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "type",
                    models.CharField(choices=[("like", "Like"), ("dislike", "Dislike")], default="like", max_length=7),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user_agent", models.CharField(blank=True, max_length=255, null=True)),
                ("ip_address", models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Multimedia",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file", models.FileField(upload_to="media/")),
                ("media_type", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="blog_app.comment",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
            },
        ),
    ]
