# Generated by Django 5.1.7 on 2025-04-08 09:42

from django.db import migrations


def add_default_categories(apps, schema_editor):
    category = apps.get_model("blog_app", "Category")

    default_categories = [
        {
            "name": "Software Development",
            "subtitle": "Building Better Systems, Code by Code",
            "description": "Explore modern software development principles, tools, and techniques to create robust, scalable solutions.",
            "slug": "software-development-thumbnail",
        },
        {
            "name": "Management & Culture",
            "subtitle": "The Heartbeat of Successful Teams",
            "description": "Strategies for leading teams and fostering organizational cultures that drive innovation and collaboration.",
            "slug": "management-culture-thumbnail",
        },
        {
            "name": "Cybersecurity",
            "subtitle": "Guarding Digital Frontiers",
            "description": "Comprehensive insights into digital security to prevent threats and safeguard critical systems.",
            "slug": "cybersecurity-thumbnail",
        },
        {
            "name": "Technology Trends",
            "subtitle": "Shaping the Future Today",
            "description": "Stay updated on emerging technologies transforming industries and societies worldwide.",
            "slug": "technology-trends-thumbnail",
        },
    ]

    for category_data in default_categories:
        if not category.objects.filter(name=category_data["name"]).exists():
            category.objects.create(**category_data)


def remove_default_categories(apps, schema_editor):
    category = apps.get_model("blog_app", "Category")

    default_category_names = [
        "Software Development",
        "Management & Culture",
        "Cybersecurity",
        "Technology Trends",
    ]

    category.objects.filter(name__in=default_category_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("blog_app", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_default_categories, remove_default_categories),
    ]
