# Generated by Django 5.1.7 on 2025-04-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_app", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="thumbnail",
            field=models.ImageField(blank=True, null=True, upload_to="category_thumbnails/"),
        ),
        migrations.AlterField(
            model_name="entry",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
