# Generated by Django 5.2 on 2025-04-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_app", "0002_auto_20250408_0942"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodeTip",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("code", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
