# Generated by Django 5.2 on 2025-04-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_app", "0003_codetip"),
    ]

    operations = [
        migrations.AddField(
            model_name="codetip",
            name="level",
            field=models.CharField(
                choices=[("junior", "Junior"), ("mid", "Mid"), ("senior", "Senior")], default="junior"
            ),
        ),
        migrations.AddField(
            model_name="codetip",
            name="tech_stack",
            field=models.CharField(choices=[("django", "Django"), ("python", "Python")], default="django"),
        ),
        migrations.AddField(
            model_name="codetip",
            name="type_of_tip",
            field=models.CharField(
                choices=[
                    ("consejo", "Consejo"),
                    ("tip", "Tip"),
                    ("dato curioso", "Dato Curioso"),
                    ("recomendación en ciberseguridad", "Recomendación en Ciberseguridad"),
                ],
                default="tip",
            ),
        ),
    ]
