# Generated by Django 5.2 on 2025-04-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_app", "0004_codetip_level_codetip_tech_stack_codetip_type_of_tip"),
    ]

    operations = [
        migrations.AddField(
            model_name="codetip",
            name="error_message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="codetip",
            name="gemini_raw_response",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="codetip",
            name="prompt_used",
            field=models.TextField(blank=True, default=""),
        ),
    ]
