# Generated by Django 5.1.7 on 2025-04-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_app", "0004_auto_20250407_1014"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="cdn_image_url",
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
