# Generated by Django 5.1.7 on 2025-04-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_app", "0004_auto_20250407_1014"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="cdn_image_public_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="entry",
            name="cdn_image_url",
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
