# Generated by Django 5.2 on 2025-04-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_app", "0005_codetip_error_message_codetip_gemini_raw_response_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="slug",
            field=models.SlugField(),
        ),
    ]
