# Generated by Django 5.2 on 2025-05-03 13:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_app", "0006_alter_entry_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeminiApiUsage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("request_count", models.IntegerField(default=0)),
                ("successful_requests", models.IntegerField(default=0)),
                ("failed_requests", models.IntegerField(default=0)),
                ("tokens_used", models.IntegerField(default=0)),
                ("average_response_time", models.FloatField(default=0)),
                ("model_name", models.CharField(default="gemini-2.5-pro-preview-03-25", max_length=100)),
                ("last_error_message", models.TextField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Gemini API Usage",
                "verbose_name_plural": "Gemini API Usage",
                "ordering": ["-date"],
            },
        ),
    ]
